### ISSUE TITLE
Add help command line option

### ISSUE THREAD

**Issue by morazow** [exasol/release-droid#127]
### Situation

At the moment, release-droid does not recognize the `-h` or `--help` commands. It shows available commands, but also terminates with an unrecognized option exception.

```
$ java -jar ../release-droid/target/release-droid-0.3.1.jar --help
usage: Release Droid
 -b,--branch <arg>      git branch (only for validation)
 -g,--goal <arg>        goal to execute
 -l,--local <arg>       local path to the repository
 -n,--name <arg>        project name
 -p,--platforms <arg>   comma-separated list of release platforms
Exception in thread "main" java.lang.IllegalArgumentException: E-RR-RUN-1: Unrecognized option: --help
        at com.exasol.releasedroid.main.UserInputParser.getCommandLine(UserInputParser.java:59)
        at com.exasol.releasedroid.main.UserInputParser.parseUserInput(UserInputParser.java:27)
        at com.exasol.releasedroid.main.Runner.main(Runner.java:28)
```

### Acceptance Criteria

- `-h` and `--help` commands are added that show usage

**Comment by chiaradiamarcelo** [comment]
Great idea
