### ISSUE TITLE
NoClassDefFoundError when releasing on Jira

### ISSUE THREAD

**Issue by kaklakariada** [exasol/release-droid#226]
```
test-db-builder-java % release-droid -lg java -n test-db-builder-java -g release     
2022-04-22 17:36:44.163 [INFO   ] Found an artifact on 'exasol/test-db-builder-java' repository. 
2022-04-22 17:36:45.606 [INFO   ] A GitHub workflow 'release_droid_print_quick_checksum.yml' has started. The Release Droid is monitoring its progress. This can take from a few minutes to a couple of hours depending on the build. 
2022-04-22 17:37:45.613 [INFO   ] Workflow is running for about 1 minutes. 
2022-04-22 17:38:26.980 [INFO   ] Checksum validation for 'exasol/test-db-builder-java' repository failed. 
2022-04-22 17:38:26.981 [INFO   ] Removing all artifacts from 'exasol/test-db-builder-java' repository. 
2022-04-22 17:38:28.148 [INFO   ] There are no artifacts on the 'exasol/test-db-builder-java' repository. 
2022-04-22 17:38:28.148 [INFO   ] Preparing a new artifact with a checksum. 
2022-04-22 17:38:28.531 [INFO   ] A GitHub workflow 'release_droid_prepare_original_checksum.yml' has started. The Release Droid is monitoring its progress. This can take from a few minutes to a couple of hours depending on the build. 
2022-04-22 17:39:28.537 [INFO   ] Workflow is running for about 1 minutes. 
2022-04-22 17:40:48.741 [INFO   ] Workflow is running for about 2 minutes. 
2022-04-22 17:41:49.555 [INFO   ] Workflow is running for about 3 minutes. 
2022-04-22 17:42:50.478 [INFO   ] Workflow is running for about 4 minutes. 
2022-04-22 17:43:51.181 [INFO   ] Workflow is running for about 5 minutes. 
2022-04-22 17:44:52.039 [INFO   ] Workflow is running for about 6 minutes. 
2022-04-22 17:45:52.874 [INFO   ] Workflow is running for about 7 minutes. 
2022-04-22 17:46:53.593 [INFO   ] Workflow is running for about 8 minutes. 
2022-04-22 17:47:54.339 [INFO   ] Workflow is running for about 9 minutes. 
2022-04-22 17:47:55.108 [INFO   ] Validation started. 
2022-04-22 17:47:56.637 [INFO   ] Releasing on MAVEN platform. 
2022-04-22 17:47:57.073 [INFO   ] A GitHub workflow 'release_droid_release_on_maven_central.yml' has started. The Release Droid is monitoring its progress. This can take from a few minutes to a couple of hours depending on the build. 
2022-04-22 17:48:57.079 [INFO   ] Workflow is running for about 1 minutes. 
2022-04-22 17:50:18.905 [INFO   ] Workflow is running for about 2 minutes. 
2022-04-22 17:50:19.642 [INFO   ] A MavenCentral release was published at: maven-central 
2022-04-22 17:50:19.841 [INFO   ] Release on platform MAVEN is finished! 
2022-04-22 17:50:19.841 [INFO   ] Validation started. 
2022-04-22 17:50:22.786 [INFO   ] Releasing on GITHUB platform. 
2022-04-22 17:50:23.925 [INFO   ] A GitHub workflow 'release_droid_upload_github_release_assets.yml' has started. The Release Droid is monitoring its progress. This can take from a few minutes to a couple of hours depending on the build. 
2022-04-22 17:51:23.928 [INFO   ] Workflow is running for about 1 minutes. 
2022-04-22 17:51:44.503 [INFO   ] A GitHub release was created at: https://github.com/exasol/test-db-builder-java/releases/tag/3.3.2 
2022-04-22 17:51:44.681 [INFO   ] Release on platform GITHUB is finished! 
2022-04-22 17:51:44.681 [INFO   ] Validation started. 
2022-04-22 17:51:44.868 [INFO   ] Releasing on JIRA platform. 
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/beans/factory/DisposableBean
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at com.atlassian.jira.rest.client.internal.async.AsynchronousHttpClientFactory.createClient(AsynchronousHttpClientFactory.java:51)
        at com.atlassian.jira.rest.client.internal.async.AsynchronousJiraRestClientFactory.create(AsynchronousJiraRestClientFactory.java:36)
        at com.atlassian.jira.rest.client.internal.async.AsynchronousJiraRestClientFactory.createWithBasicHttpAuthentication(AsynchronousJiraRestClientFactory.java:42)
        at com.exasol.releasedroid.adapter.jira.JiraAPIAdapter.createJiraClient(JiraAPIAdapter.java:63)
        at com.exasol.releasedroid.adapter.jira.JiraAPIAdapter.createTicket(JiraAPIAdapter.java:39)
        at com.exasol.releasedroid.adapter.jira.JiraReleaseMaker.createTicketRequest(JiraReleaseMaker.java:52)
        at com.exasol.releasedroid.adapter.jira.JiraReleaseMaker.makeRelease(JiraReleaseMaker.java:37)
        at com.exasol.releasedroid.usecases.release.ReleaseInteractor.releaseOnPlatform(ReleaseInteractor.java:129)
        at com.exasol.releasedroid.usecases.release.ReleaseInteractor.releaseOnPlatforms(ReleaseInteractor.java:84)
        at com.exasol.releasedroid.usecases.release.ReleaseInteractor.makeRelease(ReleaseInteractor.java:66)
        at com.exasol.releasedroid.usecases.release.ReleaseInteractor.release(ReleaseInteractor.java:53)
        at com.exasol.releasedroid.main.ReleaseDroid.run(ReleaseDroid.java:63)
        at com.exasol.releasedroid.main.Runner.main(Runner.java:46)
Caused by: java.lang.ClassNotFoundException: org.springframework.beans.factory.DisposableBean
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 22 more
```

**Comment by morazow** [comment]
I think it is because of this https://github.com/exasol/release-droid/pull/224
Sorry, I could not test the release after removing the dependency.
