### ISSUE TITLE
Validation of local repository fails when version tags start with a 'v'

### ISSUE THREAD

**Issue by kaklakariada** [exasol/release-droid#237]
Running the validate goal on a local clone of [cloud-storage-extension](https://github.com/exasol/cloud-storage-extension) fails with the following exception:

```
% release-droid -n cloud-storage-extension  -g validate -lg java -p github,jira -l .
2022-06-23 10:40:41.916 [INFO   ] Validation started. 
Exception in thread "main" java.lang.NumberFormatException: For input string: "v0"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:652)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at com.exasol.releasedroid.adapter.repository.CommonRepositoryValidator.getPossibleVersions(CommonRepositoryValidator.java:133)
        at com.exasol.releasedroid.adapter.repository.CommonRepositoryValidator.validateNewVersionWithPreviousTag(CommonRepositoryValidator.java:116)
        at com.exasol.releasedroid.adapter.repository.CommonRepositoryValidator.validateIfNewReleaseTagValid(CommonRepositoryValidator.java:105)
        at com.exasol.releasedroid.adapter.repository.CommonRepositoryValidator.validateVersion(CommonRepositoryValidator.java:83)
        at com.exasol.releasedroid.adapter.repository.CommonRepositoryValidator.validate(CommonRepositoryValidator.java:40)
        at com.exasol.releasedroid.adapter.RepositoryValidatorHelper.validateRepositories(RepositoryValidatorHelper.java:49)
        at com.exasol.releasedroid.adapter.github.GitHubPlatformValidator.validate(GitHubPlatformValidator.java:46)
        at com.exasol.releasedroid.usecases.validate.ValidateInteractor.validateForPlatform(ValidateInteractor.java:38)
        at com.exasol.releasedroid.usecases.validate.ValidateInteractor.validate(ValidateInteractor.java:28)
        at com.exasol.releasedroid.main.ReleaseDroid.run(ReleaseDroid.java:65)
        at com.exasol.releasedroid.main.Runner.main(Runner.java:46)
```

The exception occurs because this repository contains old tags like [v0.8.0](https://github.com/exasol/cloud-storage-extension/releases/tag/v0.8.0) with a `v` prefix.

## Workaround

Run RD without the `-l` flag.

## Analysis

Root cause: for local repositories RD determines the latest released version by taking the last entry returned by `Git.getRepository().getRefDatabase().getRefsByPrefix(R_TAGS)` (see [LocalRepositoryGate.java](https://github.com/exasol/release-droid/blob/main/src/main/java/com/exasol/releasedroid/adapter/repository/LocalRepositoryGate.java#L85)). In case of this repository this is `v0.8.0` instead of [2.3.1](https://github.com/exasol/cloud-storage-extension/releases/tag/2.3.1).

Accepting versions with `v` prefix won't fix the issue, because then `0.8.0` would be used as latest released version which would fail validation at a later point.

A possible solution would be to sort the result of `getRefsByPrefix()` to find the highest version number.

**Comment by ckunki** [comment]
Hi @kaklakariada: is the current ticket a duplicate of #245 ?

**Comment by kaklakariada** [comment]
Yes, I will closes this :)

**Comment by ckunki** [comment]
Only closed tickets are good tickets 😃
